---
abstract: 'The patriarch of IRC Bots'
author:
  - 'Chris Prather (chris@prather.org)'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Adam
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  MooseX::Aliases: 0.05
  MooseX::Getopt: 0.22
  MooseX::LogDispatch: 1.200
  MooseX::POE: 0.09
  MooseX::SimpleConfig: 0.03
  POE::Component::IRC: 6.12
  namespace::autoclean: 0.09
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/perigrin/adam-bot-framework.git
version: 0.04
