---
abstract: 'The patriarch of IRC Bots'
author:
  - 'Chris Prather <chris@prather.org>'
  - 'Torsten Raudssus <torsten@raudssus.de> L<http://www.raudssus.de/>'
build_requires:
  Test::Deep: 0.103
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Adam
no_index:
  directory:
    - ex
provides:
  Moses::Declare:
    file: lib/Moses/Declare.pm
    version: 0.90
  Moses::Declare::Syntax::BotKeyword:
    file: lib/Moses/Declare/Syntax/BotKeyword.pm
    version: 0.90
  Moses::Declare::Syntax::EventKeyword:
    file: lib/Moses/Declare/Syntax/EventKeyword.pm
    version: 0.90
  Moses::Declare::Syntax::PluginKeyword:
    file: lib/Moses/Declare/Syntax/PluginKeyword.pm
    version: 0.90
requires:
  MooseX::Aliases: 0.10
  MooseX::Declare: 0.34
  MooseX::Getopt: 0.37
  MooseX::LogDispatch: 1.2002
  MooseX::POE: 0.214
  MooseX::SimpleConfig: 0.09
  POE::Component::IRC: 6.64
  aliased: 0.30
  namespace::autoclean: 0.12
resources:
  homepage: http://github.com/perigrin/adam-bot-framework
  repository: git://github.com/perigrin/adam-bot-framework.git
version: 0.90
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Basic/GatherDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Basic/MakeMaker'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaProvides::Class
      name: MetaProvides::Class
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::SurgicalPodWeaver
      name: SurgicalPodWeaver
      version: 0.0018
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.12
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.200006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200006
